services:
  - type: web
    name: video-downloader-api
    runtime: python
    buildCommand: ./build.sh
    startCommand: cd api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
